stages:
  - build

.build:
  stage: build
  image: coqorg/${CI_JOB_NAME}
  before_script:
    - if [ -n "${COMPILER_EDGE}" ]; then opam switch ${COMPILER_EDGE} && eval $(opam env); fi
    - opam update -y
    - opam config list
    - opam repo list
    - opam list
  script:
    - sudo chown -R coq:coq "$CI_PROJECT_DIR"
    - make -j "$NJOBS"
    - make install
  tags:
    - ci.inria.fr
    - medium


coq:dev:
  extends: .build
